# Generated by Django 5.0.6 on 2024-06-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='is_active',
        ),
    ]
