# Generated by Django 5.0.6 on 2024-06-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_active_article_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='publication_date',
        ),
    ]
